### ISSUE TITLE
idl fetch with no arguments should install specified versions

### ISSUE THREAD

**Issue by andrewdeandrade** [uber-node/idl#58]
idl fetch with no args is supposed to only install what is in your meta.json file and not change the meta.json file. It currently has the same behavior as update.

**Comment by kriskowal** [comment]
Oddly, the evident programmed behavior until 3.1.11 was for fetch sans arguments to install the versions already installed as mentioned in idl/meta.json, but I do not understand the reasoning for this. We can discuss reopening this issue.

The new release changes `idl fetch` sans arguments to be equivalent to `idl update` explicitly.
